# Generated by Django 4.0.5 on 2022-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_used', models.BooleanField()),
            ],
        ),
    ]
