# Generated by Django 4.0.5 on 2022-06-23 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='date_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 13, 16, 7, 733973)),
        ),
    ]
